### ISSUE TITLE
Configure base path for imports.

### ISSUE THREAD

**Issue by MeoMix** [css-modules/postcss-modules-extract-imports#38]
It'd be nice to leverage a lot of the configuration from https://github.com/postcss/postcss-import and apply it here.

Specifically, I'd like to say `composes: white from 'common/css/color.css'` instead of `composes: white from '../../common/css/color.css'`

**Comment by oreshinya** [comment]
+1

**Comment by TrySound** [comment]
It's `css-loader`, `postcss-modules` or `css-modulsify` issue
