### ISSUE TITLE
Don’t use parent#push

### ISSUE THREAD

**Issue by ai** [css-modules/postcss-modules-extract-imports#59]
According PostCSS docs, `Container#push` is low level method and should not be used by plugins.

This method is for parsers only. It doesn’t contains checks as result it is easy to broke AST by putting wrong nodes.

[This line](https://github.com/css-modules/postcss-modules-extract-imports/blob/master/src/index.js#L59) produces broken AST, because it doesn’t set a `parent` property.

@geelen You should replace `push()` to `append()`.

Here is a issue because of this bug: https://github.com/ben-eb/cssnano/issues/163#issuecomment-208214467

**Comment by ai** [comment]
@geelen what do you think about it?

**Comment by ben-eb** [comment]
Can we get this fixed? 👍

**Comment by geelen** [comment]
Fixed at https://github.com/css-modules/postcss-modules-extract-imports/commit/67ffacf25245549539a6d311198de943b49532b5 <3

**Comment by geelen** [comment]
Published 1.0.1 as well

**Comment by ben-eb** [comment]
Thanks!
